/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2020-07-18 09:35:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.StudentD;
import vo.Student;
import dao.ScoreD;
import vo.Score;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.Score");
    _jspx_imports_classes.add("vo.Student");
    _jspx_imports_classes.add("dao.ScoreD");
    _jspx_imports_classes.add("dao.StudentD");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>main</title>\n");
      out.write("    <link href=\"../resources/css/default.css\" rel=\"stylesheet\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");

    Student student = (Student) session.getAttribute("info");

      out.write("\n");
      out.write("<div id=\"page\" class=\"container\">\n");
      out.write("    <div id=\"header\">\n");
      out.write("        <div id=\"logo\">\n");
      out.write("            <img src=\"../userImg/");
      out.print(student.getId());
      out.write(".jpeg\"/>\n");
      out.write("            <h1>");
      out.print(student.getName());
      out.write("</h1>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"menu\">\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"personal.jsp\">Thông tin sinh viên</a></li>\n");
      out.write("                <li class=\"current_page_item\"><a href=\"main.jsp\">Kết quả</a></li>\n");
      out.write("                <li><a onclick=\"return confirm('Xác nhận đăng xuất');\" href=\"../exit\">Đăng xuất</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"main\">\n");
      out.write("        <div class=\"top\">\n");
      out.write("            <h2>Kết quả</h2>\n");
      out.write("            <hr/>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"table\">\n");
      out.write("            <table width=\"800\" frame=\"box\" align=\"center\">\n");
      out.write("                <tr>\n");
      out.write("                    <th height=\"35\">Mã sinh viên</th>\n");
      out.write("                    <th>Họ tên</th>\n");
      out.write("                    <th>Chuyên ngành</th>\n");
      out.write("                    <th>Điểm CSDL</th>\n");
      out.write("                    <th>Điểm Android</th>\n");
      out.write("                    <th>Điểm JavaWeb</th>\n");
      out.write("                    <th>Tùy chọn</th>\n");
      out.write("                </tr>\n");
      out.write("                ");

                    try {
                        ScoreD scoD = new ScoreD();
                        StudentD stuD = new StudentD();
                        Score stu = scoD.findWithId(student.getId());
                        String name = stuD.findWithId(student.getId()).getName();
                        String major = stuD.findWithId(student.getId()).getMajor();
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td height=\"35\">");
      out.print(stu.getId());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print(name);
      out.write("</td>\n");
      out.write("                    <td>");
      out.print(major);
      out.write("</td>\n");
      out.write("                    <td>");
      out.print(stu.getDatabase());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print(stu.getAndroid());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print(stu.getJsp());
      out.write("</td>\n");
      out.write("                    <td><a href=\"pdf.jsp?id=");
      out.print(stu.getId());
      out.write("&name=");
      out.print(name);
      out.write("&major=");
      out.print(major);
      out.write("&database=");
      out.print(stu.getDatabase());
      out.write("&android=");
      out.print(stu.getAndroid());
      out.write("&jsp=");
      out.print(stu.getJsp());
      out.write("\">PDF</a></td>\n");
      out.write("                </tr>\n");
      out.write("                ");

                    }
                    catch (Exception e){
                        out.print(e);
                    }
                
      out.write("\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
